### ISSUE TITLE
gatsby build fails on Netlify with this plugin installed

### ISSUE THREAD

**Issue by samgermain** [NoriSte/gatsby-plugin-preconnect#455]
The plugin is installed and i have the plugin included in my `gatsby-config.js`
If I run `npm remove gatsby-plugin-preconnect` and comment of the `gatsby-config` the build no longer fails 

**gatsby-config.js**
    
```
{
      resolve: 'gatsby-plugin-preconnect',
      options: {
        domains: [
          "https://ir-ca.amazon-adsystem.com",
          "https://fls-na.amazon-adsystem.com",
          "https://fonts.googleapis.com",
          "https://ws-na.assoc-amazon.com",
          "https://www.google-analytics.com"
        ],
      },
    },
```

**Error log**

```
7:50:55 PM: Build ready to start
7:50:57 PM: build-image version: ca811f47d4c1cbd1812d1eb6ecb0c977e86d1a1d
7:50:57 PM: build-image tag: v3.3.20
7:50:57 PM: buildbot version: 78b5536ab4f742c26705d3e953381b9cde6e22ef
7:50:57 PM: Fetching cached dependencies
7:50:57 PM: Starting to download cache of 254.7KB
7:50:57 PM: Finished downloading cache in 76.168856ms
7:50:57 PM: Starting to extract cache
7:50:57 PM: Failed to fetch cache, continuing with build
7:50:57 PM: Starting to prepare the repo for build
7:50:58 PM: No cached dependencies found. Cloning fresh repo
7:50:58 PM: git clone https://github.com/samgermain/sudSaskV2
7:51:07 PM: Preparing Git Reference refs/heads/production
7:51:09 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'public' versus 'public/' in the Netlify UI
7:51:09 PM: Starting build script
7:51:09 PM: Installing dependencies
7:51:09 PM: Python version set to 2.7
7:51:10 PM: Downloading and installing node v14.4.0...
7:51:10 PM: Downloading https://nodejs.org/dist/v14.4.0/node-v14.4.0-linux-x64.tar.xz...
7:51:11 PM: Computing checksum with sha256sum
7:51:11 PM: Checksums matched!
7:51:14 PM: Now using node v14.4.0 (npm v6.14.5)
7:51:14 PM: Started restoring cached build plugins
7:51:14 PM: Finished restoring cached build plugins
7:51:14 PM: Attempting ruby version 2.6.2, read from environment
7:51:15 PM: Using ruby version 2.6.2
7:51:15 PM: Using PHP version 5.6
7:51:15 PM: 5.2 is already installed.
7:51:15 PM: Using Swift version 5.2
7:51:15 PM: Started restoring cached node modules
7:51:15 PM: Finished restoring cached node modules
7:51:16 PM: Installing NPM modules using NPM version 6.14.5
7:52:05 PM: > sharp@0.25.4 install /opt/build/repo/node_modules/sharp
7:52:05 PM: > (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
7:52:06 PM: info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-linux-x64.tar.gz
7:52:08 PM: > node-sass@4.14.1 install /opt/build/repo/node_modules/node-sass
7:52:08 PM: > node scripts/install.js
7:52:09 PM: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-83_binding.node
7:52:09 PM: Download complete
7:52:09 PM: Binary saved to /opt/build/repo/node_modules/node-sass/vendor/linux-x64-83/binding.node
7:52:09 PM: Caching binary to /opt/buildhome/.npm/node-sass/4.14.1/linux-x64-83_binding.node
7:52:10 PM: > core-js@2.6.11 postinstall /opt/build/repo/node_modules/@babel/polyfill/node_modules/core-js
7:52:10 PM: > node -e "try{require('./postinstall')}catch(e){}"
7:52:10 PM: > core-js@2.6.11 postinstall /opt/build/repo/node_modules/babel-polyfill/node_modules/core-js
7:52:10 PM: > node -e "try{require('./postinstall')}catch(e){}"
7:52:10 PM: > core-js@2.6.11 postinstall /opt/build/repo/node_modules/babel-runtime/node_modules/core-js
7:52:10 PM: > node -e "try{require('./postinstall')}catch(e){}"
7:52:10 PM: > core-js@3.6.5 postinstall /opt/build/repo/node_modules/core-js
7:52:10 PM: > node -e "try{require('./postinstall')}catch(e){}"
7:52:10 PM: > core-js-pure@3.6.5 postinstall /opt/build/repo/node_modules/core-js-pure
7:52:10 PM: > node -e "try{require('./postinstall')}catch(e){}"
7:52:10 PM: > core-js@2.6.11 postinstall /opt/build/repo/node_modules/gatsby/node_modules/core-js
7:52:10 PM: > node -e "try{require('./postinstall')}catch(e){}"
7:52:12 PM: > gatsby-telemetry@1.3.14 postinstall /opt/build/repo/node_modules/gatsby-telemetry
7:52:12 PM: > node src/postinstall.js || true
7:52:12 PM: > gatsby-telemetry@1.3.19 postinstall /opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli/node_modules/gatsby-telemetry
7:52:12 PM: > node src/postinstall.js || true
7:52:12 PM: > cwebp-bin@5.1.0 postinstall /opt/build/repo/node_modules/cwebp-bin
7:52:12 PM: > node lib/install.js
7:52:13 PM:   ✔ cwebp pre-build test passed successfully
7:52:13 PM: > mozjpeg@6.0.1 postinstall /opt/build/repo/node_modules/mozjpeg
7:52:13 PM: > node lib/install.js
7:52:14 PM:   ✔ mozjpeg pre-build test passed successfully
7:52:14 PM: > pngquant-bin@5.0.2 postinstall /opt/build/repo/node_modules/pngquant-bin
7:52:14 PM: > node lib/install.js
7:52:14 PM:   ✔ pngquant pre-build test passed successfully
7:52:14 PM: > gatsby-cli@2.12.60 postinstall /opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli
7:52:14 PM: > node scripts/postinstall.js
7:52:14 PM: > gatsby@2.23.11 postinstall /opt/build/repo/node_modules/gatsby
7:52:14 PM: > node scripts/postinstall.js
7:52:15 PM: > node-sass@4.14.1 postinstall /opt/build/repo/node_modules/node-sass
7:52:15 PM: > node scripts/build.js
7:52:15 PM: Binary found at /opt/build/repo/node_modules/node-sass/vendor/linux-x64-83/binding.node
7:52:15 PM: Testing binary
7:52:15 PM: Binary is fine
7:52:18 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
7:52:18 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
7:52:18 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/chokidar/node_modules/fsevents):
7:52:18 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
7:52:18 PM: added 2443 packages from 1438 contributors and audited 2453 packages in 61.852s
7:52:21 PM: 156 packages are looking for funding
7:52:21 PM:   run `npm fund` for details
7:52:21 PM: found 0 vulnerabilities
7:52:21 PM: NPM modules installed
7:52:21 PM: Started restoring cached go cache
7:52:21 PM: Finished restoring cached go cache
7:52:21 PM: Installing Go version 1.12
7:52:28 PM: unset GOOS;
7:52:28 PM: unset GOARCH;
7:52:28 PM: export GOROOT='/opt/buildhome/.gimme_cache/versions/go1.12.linux.amd64';
7:52:28 PM: export PATH="/opt/buildhome/.gimme_cache/versions/go1.12.linux.amd64/bin:${PATH}";
7:52:28 PM: go version >&2;
7:52:28 PM: export GIMME_ENV="/opt/buildhome/.gimme_cache/env/go1.12.linux.amd64.env"
7:52:28 PM: go version go1.12 linux/amd64
7:52:28 PM: Installing missing commands
7:52:28 PM: Verify run directory
7:52:29 PM: ​
7:52:29 PM: ┌─────────────────────────────┐
7:52:29 PM: │        Netlify Build        │
7:52:29 PM: └─────────────────────────────┘
7:52:29 PM: ​
7:52:29 PM: ❯ Version
7:52:29 PM:   @netlify/build 2.0.27
7:52:29 PM: ​
7:52:29 PM: ❯ Flags
7:52:29 PM:   deployId: 5f0d0f7f023dbc6fa97c64bc
7:52:29 PM:   mode: buildbot
7:52:29 PM: ​
7:52:29 PM: ❯ Current directory
7:52:29 PM:   /opt/build/repo
7:52:29 PM: ​
7:52:29 PM: ❯ Config file
7:52:29 PM:   No config file was defined: using default values.
7:52:29 PM: ​
7:52:29 PM: ❯ Context
7:52:29 PM:   production
7:52:29 PM: ​
7:52:29 PM: ❯ Loading plugins
7:52:29 PM:    - netlify-plugin-submit-sitemap@0.1.4 from Netlify app
7:52:29 PM: ​
7:52:29 PM: ┌───────────────────────────────────┐
7:52:29 PM: │ 1. Build command from Netlify app │
7:52:29 PM: └───────────────────────────────────┘
7:52:29 PM: ​
7:52:29 PM: $ gatsby build
7:52:31 PM: /opt/build/repo/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
7:52:31 PM:         throw ex;
7:52:31 PM:         ^
7:52:31 PM: Error: Cannot find module 'ink'
7:52:31 PM: Require stack:
7:52:31 PM: - /opt/build/repo/node_modules/ink-box/dist.js
7:52:31 PM: - /opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/cli.js
7:52:31 PM: - /opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/index.js
7:52:31 PM: - /opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli/lib/recipes.js
7:52:31 PM: - /opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli/lib/create-cli.js
7:52:31 PM: - /opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli/lib/index.js
7:52:31 PM: - /opt/build/repo/node_modules/gatsby/dist/bin/gatsby.js
7:52:31 PM: - /opt/build/repo/node_modules/gatsby/cli.js
7:52:31 PM:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
7:52:31 PM:     at Function.Module._load (internal/modules/cjs/loader.js:898:27)
7:52:31 PM:     at Module.require (internal/modules/cjs/loader.js:1089:19)
7:52:31 PM:     at require (internal/modules/cjs/helpers.js:73:18)
7:52:31 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/ink-box/dist.js:5:12)
7:52:31 PM:     at Module._compile (internal/modules/cjs/loader.js:1200:30)
7:52:31 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
7:52:31 PM:     at Module.load (internal/modules/cjs/loader.js:1049:32)
7:52:31 PM:     at Function.Module._load (internal/modules/cjs/loader.js:937:14)
7:52:31 PM:     at Module.require (internal/modules/cjs/loader.js:1089:19) {
7:52:31 PM:   code: 'MODULE_NOT_FOUND',
7:52:31 PM:   requireStack: [
7:52:31 PM:     '/opt/build/repo/node_modules/ink-box/dist.js',
7:52:31 PM:     '/opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/cli.js',
7:52:31 PM:     '/opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli/node_modules/gatsby-recipes/dist/index.js',
7:52:31 PM:     '/opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli/lib/recipes.js',
7:52:31 PM:     '/opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli/lib/create-cli.js',
7:52:31 PM:     '/opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli/lib/index.js',
7:52:31 PM:     '/opt/build/repo/node_modules/gatsby/dist/bin/gatsby.js',
7:52:31 PM:     '/opt/build/repo/node_modules/gatsby/cli.js'
7:52:31 PM:   ]
7:52:31 PM: }
7:52:31 PM: ​
7:52:31 PM: ┌─────────────────────────────┐
7:52:31 PM: │   "build.command" failed    │
7:52:31 PM: └─────────────────────────────┘
7:52:31 PM: ​
7:52:31 PM:   Error message
7:52:31 PM:   Command failed with exit code 7: gatsby build
7:52:31 PM: ​
7:52:31 PM:   Error location
7:52:31 PM:   In Build command from Netlify app:
7:52:31 PM:   gatsby build
7:52:31 PM: ​
7:52:31 PM:   Resolved config
7:52:31 PM:   build:
7:52:31 PM:     command: gatsby build
7:52:31 PM:     commandOrigin: ui
7:52:31 PM:     environment:
7:52:31 PM:       - NODE_VERSION
7:52:31 PM:     publish: /opt/build/repo/public
7:52:31 PM:   plugins:
7:52:31 PM:     - inputs: {}
7:52:31 PM:       origin: ui
7:52:31 PM:       package: netlify-plugin-submit-sitemap
7:52:31 PM: Caching artifacts
7:52:31 PM: Started saving node modules
7:52:31 PM: Finished saving node modules
7:52:31 PM: Started saving build plugins
7:52:31 PM: Finished saving build plugins
7:52:31 PM: Started saving pip cache
7:52:31 PM: Finished saving pip cache
7:52:31 PM: Started saving emacs cask dependencies
7:52:31 PM: Finished saving emacs cask dependencies
7:52:31 PM: Started saving maven dependencies
7:52:31 PM: Finished saving maven dependencies
7:52:31 PM: Started saving boot dependencies
7:52:31 PM: Finished saving boot dependencies
7:52:31 PM: Started saving go dependencies
7:52:33 PM: Finished saving go dependencies
7:52:36 PM: Error running command: Build script returned non-zero exit code: 1
7:52:36 PM: Failing build: Failed to build site
7:52:36 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
7:52:36 PM: Finished processing build request in 1m39.308836962s
```

**Comment by NoriSte** [comment]
Did you mean `npm uninstall`? I didn't know about `npm remove`.

Does it work on your machine?

Anyway, you should isolate the problem, start a new Gatsby project, add the plug-in, build it on Netlify and check if it works. Then, piece after piece, add all other plugins and your website code and check, then share with us the minimal configuration to reproduce the error.

If you prefer you could do the opposite, remove one plugin at a time and check if the build works, when you have detected which are the plugins that break the build, check their code and report your thoughts. This way we cannot help you because of the wider spectrum of possibilities but it could help you to find the problem 😉

**Comment by NoriSte** [comment]
Is `ink` in the dependency list of the package.json?

**Comment by NoriSte** [comment]
Ehi @samgermain, I close this issue, feel free to re-open it with more info 😉
